[phases.setup]
nixPkgs = ["python311", "redis", "gcc", "postgresql_16.dev"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[processes]
web    = "gunicorn a_core.wsgi:application --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 4"
worker = "celery -A a_core worker -l info --queues default"
