"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from environ import Env
import stripe
from django.utils.encoding import force_str
import django.utils.encoding
import cloudinary
import cloudinary_storage
import sentry_sdk

sentry_sdk.init(
    dsn="https://1fad0f8723ff747178877646366f144a@o4509562693615616.ingest.us.sentry.io/4509562695581696",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 2048 * 2048  # en octets



django.utils.encoding.force_text = force_str

BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
Env.read_env(env_file=BASE_DIR / '.env')


CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'



STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')
DOMAIN = 'https://kodoshin.ai'

stripe.api_key = STRIPE_SECRET_KEY

#FERNET_FIELDS = {
#    "default_ttl": None,
#}

FERNET_KEYS = [
    env('FERNET_KEY'),
]

ENVIRONMENT = env('ENVIRONMENT', default='production')
print(ENVIRONMENT)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [ 'https://kodoshin.ai' ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_htmx',
    'import_export',
    'allauth',
    'storages',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'a_home',
    'a_projects',
    #'a_users',
    'a_users.apps.AUsersConfig',
    'git_auth',
    'b_coding',
    'b_insights',
    'b_planning',
    'management',
    'tasks',
    'cloudinary',
    'cloudinary_storage',
    'newsletter',
]


SITE_ID = 1

if ENVIRONMENT != 'development':
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'a_users.middleware.ProfileCompletionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'

if ENVIRONMENT == 'development':
    SOCIALACCOUNT_PROVIDERS = {
        'github': {
            'APP': {
                'client_id': env('DEV_SOCIAL_PROVIDER_CLIENT'),
                'secret': env('DEV_SOCIAL_PROVIDER_SECRET'),
                'key': '',
                #'redirect_uri': 'https://fc8d-206-176-138-38.ngrok-free.app//accounts/github/login/callback'
            }
        }
    }
else :
    SOCIALACCOUNT_PROVIDERS = {
        'github': {
            'APP': {
                'client_id': env('PROD_SOCIAL_PROVIDER_CLIENT') ,
                'secret': env('PROD_SOCIAL_PROVIDER_SECRET'),
                'key': '',
                # 'redirect_uri': 'https://fc8d-206-176-138-38.ngrok-free.app//accounts/github/login/callback'
            }
        }
    }



ROOT_URLCONF = 'a_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'a_core.context_processors.reset_daily_credits',
            ],
        },
    },
]

WSGI_APPLICATION = 'a_core.wsgi.application'

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'KODOSHIN', #env('PGNAME'),
        'USER': 'mahdi', #env('PGUSER'),
        'PASSWORD': 'Aa25120894', #env('PGPASSWORD'),
        'HOST': 'kodoshin-dev-server.postgres.database.azure.com', #env('PGHOST'),
        'PORT': '5432', #env('PGPORT'),
    }
}

"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DBNAME'),
        'USER': env('DBUSER'),
        'PASSWORD': env('DBPASSWORD'),
        'HOST': 'ballast.proxy.rlwy.net',
        'PORT': '26747',
    }
}


"""
POSTGRES_LOCALLY = False
if ENVIRONMENT == 'production' or POSTGRES_LOCALLY == True:
    DATABASES['default'] = dj_database_url.parse(env('DATABASE_URL'))
"""

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#################################################### CLOUDINARY ################################################################################3
# Configuration pour les fichiers statiques
# Configuration Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}

# Backend pour les médias
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Facultatif : backend pour les statiques
#STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
if ENVIRONMENT == 'development':
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # Compression + hash fingerprint pour le cache-busting
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Configuration pour les fichiers médias
#MEDIA_URL = f"{AZURE_CUSTOM_DOMAIN}/{AZURE_MEDIA_CONTAINER}/"
#DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"

################################################################################################################################################3


STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

#MEDIA_URL = 'media/'
#MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'

#ACCOUNT_SIGNUP_REDIRECT_URL = "{% url 'account_signup' %}?next={% url 'profile' %}"
if ENVIRONMENT == 'development':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.sendgrid.net')   # ou votre SMTP
    EMAIL_PORT = env('EMAIL_PORT', default=587)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='apikey')    # SendGrid ⇒ « apikey »
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')  # clé réelle dans le .env
    EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'no-reply@kodoshin.ai'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION    = 'mandatory'      # ← déclenche l’e-mail de confirmation
ACCOUNT_CONFIRM_EMAIL_ON_GET  = True
ENCRYPTION_KEY = "wj67r5s6sxIHe5tkqvC6ZJ7L6ekr61S5lS3CXXjXXgA="


GITHUB_WEBHOOK_URL = "https://kodoshin.ai/projects/github/webhook/"
