"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os
from storages.backends.azure_storage import AzureStorage


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+0n(2jhp%ys2aa(ezw9obo)jx2w1e0&jgit(46qo19c-po68u+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['kodoshin.azurewebsites.net', 'kodoshin‑ebaaaphdd5gdhvdg.canadacentral‑01.azurewebsites.net']
#ALLOWED_HOSTS = ['fc8d-206-176-138-38.ngrok-free.app','http://127.0.0.1:8000']
#CSRF_TRUSTED_ORIGINS = ['https://fc8d-206-176-138-38.ngrok-free.app','http://127.0.0.1:8000']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_htmx',
    'import_export',
    'allauth',
    'storages',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'a_home',
    'a_projects',
    'a_users',
    'git_auth',
    'b_coding',
    'management'
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'a_users.middleware.ProfileCompletionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'


SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'APP': {
            'client_id': 'Ov23liw9AoK39xGtiPSj',
            'secret': '8adf0e0159c92e584fe721c057e4a4dc9c171fba',
            'key': '',
            #'redirect_uri': 'https://fc8d-206-176-138-38.ngrok-free.app//accounts/github/login/callback'
        }
    }
}



ROOT_URLCONF = 'a_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'a_core.context_processors.reset_daily_credits',
            ],
        },
    },
]

WSGI_APPLICATION = 'a_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
env = environ.Env()
env_path = os.path.join(BASE_DIR, ".env")  # BASE_DIR est défini en haut de settings.py
if os.path.exists(env_path):
    environ.Env.read_env(env_path)
    #print("Fichier .env chargé avec succès")
else:
    print("Le fichier .env est manquant !")


"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}
"""


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'KODOSHIN',
        'USER': 'mahdi',
        'PASSWORD': 'Aa25120894',
        'HOST': 'kodoshin-dev-server.postgres.database.azure.com',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Lire les variables depuis .env
#AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_NAME = 'kodoshinstaticfiles'
#AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
AZURE_ACCOUNT_KEY = 'mN/+Rts/vp6KbRjOLdmSRA3I1mCGsGH5wg9JwckK8rqKkmnCom7ija34lCIlLCPIulMAzwmfH+AB+AStS1BkMQ=='

#AZURE_STATIC_CONTAINER = env("AZURE_STATIC_CONTAINER", default="staticfiles")
#AZURE_MEDIA_CONTAINER = env("AZURE_MEDIA_CONTAINER")
AZURE_MEDIA_CONTAINER = 'mediafiles'

AZURE_CUSTOM_DOMAIN = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net"

# Configuration pour les fichiers statiques
#STATIC_URL = f"{AZURE_CUSTOM_DOMAIN}/{AZURE_STATIC_CONTAINER}/"
#STATICFILES_STORAGE = "storages.backends.azure_storage.AzureStorage"

# Configuration pour les fichiers médias
MEDIA_URL = f"{AZURE_CUSTOM_DOMAIN}/{AZURE_MEDIA_CONTAINER}/"
DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"


STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

#MEDIA_URL = 'media/'
#MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'

#ACCOUNT_SIGNUP_REDIRECT_URL = "{% url 'account_signup' %}?next={% url 'profile' %}"
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ENCRYPTION_KEY = "wj67r5s6sxIHe5tkqvC6ZJ7L6ekr61S5lS3CXXjXXgA="


GITHUB_WEBHOOK_URL = "https://fc8d-206-176-138-38.ngrok-free.app"
